"""Build the public Three-Statement Analysis payload and downloadable artifacts.

The historical facts are curated from official DMX consolidated statements with
page/sheet locators. FY2023 is retained only as the expressly unaudited comparative
column in the FY2024 filing. This script validates accounting identities and source
registry lineage before publishing any output.
"""

from __future__ import annotations

import csv
import json
import shutil
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ANALYTICS_SRC = REPO_ROOT / "analytics" / "src"
if str(ANALYTICS_SRC) not in sys.path:
    sys.path.insert(0, str(ANALYTICS_SRC))

from mwg_dmx_analytics.data_io import (  # noqa: E402
    file_sha256,
    load_financial_facts,
    load_source_documents,
    to_jsonable,
    write_json,
)
from mwg_dmx_analytics.three_statement import build_three_statement_analysis  # noqa: E402
from mwg_dmx_analytics.validation import (  # noqa: E402
    has_blocking_errors,
    validate_dataset,
    validation_summary,
)


FACTS_PATH = REPO_ROOT / "data" / "processed" / "dmx_three_statement_facts.csv"
SOURCES_PATH = REPO_ROOT / "data" / "processed" / "dmx_three_statement_sources.csv"
NORMALIZATION_PATH = (
    REPO_ROOT / "data" / "processed" / "dmx_normalization_adjustments.csv"
)
REGISTRY_PATH = REPO_ROOT / "data" / "source_registry.csv"

CANONICAL_OUTPUT = (
    REPO_ROOT / "data" / "processed" / "dmx_three_statement_analysis.json"
)
APP_OUTPUT = REPO_ROOT / "app" / "data" / "three-statement-analysis.json"
PUBLIC_JS_OUTPUT = REPO_ROOT / "public" / "three-statement-data.js"
DOWNLOAD_DIR = REPO_ROOT / "public" / "downloads"
DOWNLOAD_JSON = DOWNLOAD_DIR / "dmx_three_statement_analysis.json"
DOWNLOAD_FACTS = DOWNLOAD_DIR / "dmx_three_statement_facts.csv"
DOWNLOAD_NORMALIZATION = DOWNLOAD_DIR / "dmx_normalization_adjustments.csv"
DOWNLOAD_MANIFEST = DOWNLOAD_DIR / "three_statement_manifest.json"


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def verify_sources_against_registry() -> None:
    registry = {row["source_id"]: row for row in _read_csv(REGISTRY_PATH)}
    source_rows = _read_csv(SOURCES_PATH)
    missing = [row["source_document_id"] for row in source_rows if row["source_document_id"] not in registry]
    if missing:
        raise ValueError(f"Three-statement sources are missing from source_registry.csv: {missing}")
    mismatches: list[str] = []
    for row in source_rows:
        source_id = row["source_document_id"]
        registered = registry[source_id]
        for source_field, registry_field in (
            ("source_url", "direct_url"),
            ("sha256", "sha256"),
            ("retrieved_at", "retrieved_at"),
        ):
            if row[source_field].strip() != registered[registry_field].strip():
                mismatches.append(f"{source_id}:{source_field}")
    if mismatches:
        raise ValueError(f"Three-statement source metadata drifted from registry: {mismatches}")


def _write_javascript_payload(path: Path, analysis: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(
        to_jsonable(analysis), indent=2, ensure_ascii=False, sort_keys=True
    )
    path.write_text(
        "// Generated by scripts/build_three_statement_analysis.py\n"
        f"window.DMX_THREE_STATEMENT_ANALYSIS = {payload};\n",
        encoding="utf-8",
        newline="\n",
    )


def build() -> dict[str, object]:
    verify_sources_against_registry()
    facts = load_financial_facts(FACTS_PATH)
    sources = load_source_documents(SOURCES_PATH)
    validations = validate_dataset(facts, sources)
    if has_blocking_errors(validations):
        raise ValueError(f"Generic fact validation failed: {validation_summary(validations)}")
    warning_failures = [
        result for result in validations if result.severity == "warning" and not result.passed
    ]
    if warning_failures:
        raise ValueError(
            "Three-statement publication requires zero unresolved validation warnings: "
            f"{[result.message for result in warning_failures]}"
        )

    analysis = build_three_statement_analysis(
        facts,
        normalization_path=NORMALIZATION_PATH,
    )
    analysis["generic_validation"] = validation_summary(validations)

    for target in (CANONICAL_OUTPUT, APP_OUTPUT, DOWNLOAD_JSON):
        write_json(target, analysis)
    _write_javascript_payload(PUBLIC_JS_OUTPUT, analysis)

    DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copy2(FACTS_PATH, DOWNLOAD_FACTS)
    shutil.copy2(NORMALIZATION_PATH, DOWNLOAD_NORMALIZATION)

    published = [
        DOWNLOAD_JSON,
        DOWNLOAD_FACTS,
        DOWNLOAD_NORMALIZATION,
        PUBLIC_JS_OUTPUT,
    ]
    manifest = {
        "data_version": analysis["metadata"]["data_version"],  # type: ignore[index]
        "source_fact_count": len(facts),
        "accounting_check_summary": analysis["check_summary"],
        "generic_validation": analysis["generic_validation"],
        "files": {
            path.relative_to(REPO_ROOT).as_posix(): {
                "bytes": path.stat().st_size,
                "sha256": file_sha256(path),
            }
            for path in published
        },
    }
    write_json(DOWNLOAD_MANIFEST, manifest)
    return analysis


def main() -> None:
    analysis = build()
    summary = analysis["check_summary"]
    print(
        "Three-statement analysis built: "
        f"{analysis['metadata']['fact_count']} facts; "
        f"{summary['passed']}/{summary['checks']} accounting checks passed"
    )
    print(f"Canonical payload: {CANONICAL_OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
